name: Deploy to Bluehost via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH (SFTP)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: kae.vtw.mybluehost.me
          username: kaevtwmy
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './*'
          remote_path: '/home4/kaevtwmy/public_html/website_471ce401/'
